### PR TITLE
Added demonstration notebooks for new Galactic Plane science metrics

### PR DESCRIPTION
**Pull request by rachel3834**
Notebooks demonstrating the use of Galactic Plane metrics

### CODE REVIEW

**Comment by rachel3834** [comment]
Revised PR to include an extra notebook for the RGES spatial overlap metric.

**Comment by rhiannonlynne** [comment]
Hi Rachel, I'd rather not include all of the npz files into the repo if we can avoid it, but also I'd like to check in with you if these notebooks would still be something you'd like to contribute to this repo - given the https://github.com/lsst/rubin_sim_notebooks/blob/main/maf/science/GalacticPlane%20Metrics.ipynb notebook, but also some of these notebooks don't use the metric in MAF, but rather show developing the metrics themselves.

**Comment by rachel3834** [comment]
Hi Lynne,

I agree that we shouldn't need to include npz files in the repo.  The
notebooks for the Galactic Plane metrics have been superceded some what,
too.  I am happy to contribute a revised notebook describing the GP metrics
if that is helpful.  I originally assumed that the notebooks were intended
to provide an alternative form of documentation describing what the metric
evaluates and how to interpret it, but perhaps that is not the case?

**Comment by rhiannonlynne** [comment]
You have that correctly - the notebooks are intended to provide a way to document and explain what the metric does and how to interpret the results, and give examples of what the metric results should be. 
Because of the last part, we prefer to have the notebook import the metric from MAF, rather than show a copy of the metric (which could diverge from the version in rubin_sim either accidentally or on purpose - and it can be hard to tell whether changes were intended or not, sometimes). 
The notebook I pointed you to includes more documentation about the map as well as the metric, so perhaps it's a bit clumped up overall, but does calculate and show the outputs of the metrics (it could use more text describing what the metrics are doing), and then shows the outputs of the metrics over several different runs. 
It's true that splitting that notebook up into two parts (one for the map and one for the metrics) and adding more text would be good. Keeping all of the galactic plane metrics together in one notebook also seems good, as they are very related and make much more sense together.

**Comment by rachel3834** [comment]
OK, thanks for the feedback, I'm happy to update this notebook.

**Pull request closed without merging**
